---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: cron_email_backup_fail_check
  pillars-from-files:
    cron_email_backup_fail_check.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
        - cron_email_backup_fail_check

platforms:
- name: debian-with-cron
  driver_config:
    image: renskiy/cron:debian
#   - name: centos
#     driver_config:
#       run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
          - cron_email_backup_fail_check

verifier:
  name: shell
  remote_exec: false
  command: .venv/bin/py.test -s --connection=docker  --hosts=root@$KITCHEN_CONTAINER_ID --html=reports/$KITCHEN_INSTANCE.html --self-contained-html --junit-xml=reports/junit-$KITCHEN_INSTANCE.xml tests/integration/$KITCHEN_SUITE
