hosts:
  baaken@bienert.it:
    nas_name: ""

  baatz@bienert.it:
    nas_name: ""

  bleser@bienert.it:
    nas_name: ""

  boemmel@bienert.it:
    nas_name: ""

  bremen@bienert.it:
    nas_name: ""

  bundb@bienert.it:
    nas_name: ""

  grote@bienert.it:
    nas_name: ""

  karlein@bienert.it:
    nas_name: ""

  krick@bienert.it:
    nas_name: ""

  mvz@bienert.it:
    nas_name: ""

  mvzuro@bienert.it:
    nas_name: ""

  mvzurohomberg@bienert.it:
    nas_name: ""

  outsitemedia@bienert.it:
    nas_name: ""

  praxismitherz@bienert.it:
    nas_name: ""

  praxismitkoepfchen@bienert.it:
    nas_name: ""

  schafhausen@bienert.it:
    nas_name: ""

  stephan@bienert.it:
    nas_name: ""

  wischt@bienert.it:
    nas_name: ""
